/**
 * Contains action types for redux.
 * @module redux/types
 */

//Project
export const GET_PUBLIC_PROJECTS = "GET_PUBLIC_PROJECTS";
export const GET_PRIVATE_PROJECTS = "GET_PRIVATE_PROJECTS";
export const GET_ARCHIVED_PROJECTS = "GET_ARCHIVED_PROJECTS";

export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const GET_REQUIREMENTS_BY_PROJECT_ID = "GET_REQUIREMENTS_BY_PROJECT_ID";
export const POST_REQUIREMENT_TO_PROJECT = "POST_REQUIREMENT_TO_PROJECT";
export const DELETE_REQUIREMENT_TO_PROJECT = "DELETE_REQUIREMENT_TO_PROJECT";
export const POST_PROJECT_NEW = "POST_PROJECT_NEW";
export const CHANGE_PROJECTS_TABLE_MODE = "CHANGE_PROJECTS_TABLE_MODE";
export const DELETE_PROJECT = "DELETE_PROJECT";

//Projectform
export const CHANGE_PROJECT_FORM_MODE = "CHANGE_PROJECT_FORM_MODE";
export const PROJECT_CLICKED = "PROJECT_CLICKED";
export const FILL_PROJECT_FORM = "FILL_PROJECT_FORM";

//ProjectTable
export const PROJECT_TABLE_PAGE = "PROJECT_TABLE_PAGE";
export const PROJECT_TABLE_ROWS = "PROJECT_TABLE_ROWS";

//UserTable
export const USER_TABLE_PAGE = "USER_TABLE_PAGE";
export const USER_TABLE_ROWS = "USER_TABLE_ROWS";

//Requirement
export const GET_ALL_REQUIREMENTS = "GET_ALL_REQUIREMENTS";
export const GET_ALL_CATEGORY_NAMES = "GET_CATEGORIES";
export const UPDATE_FILTER_REQUIREMENT_LIST = "UPDATE_FILTER_REQUIREMENT_LIST";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const POST_UPDATE_REQUIREMENT = "POST_UPDATE_REQUIREMENT";
export const ADD_REQUIREMENT = "ADD_REQUIREMENT";
export const UPDATE_REQUIREMENT = "UPDATE_REQUIREMENT";
export const DELETE_REQUIREMENT = "DELETE_REQUIREMENT";
export const ADD_TO_FILTER = "ADD_TO_FILTER";
export const REMOVE_FROM_FILTER = "REMOVE_FROM_FILTER";

//SideMenu
export const CHANGE_SIDE_MENU_MODE = "CHANGE_SIDE_MENU_MODE";

//User
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USERS = "GET_USERS";
export const GET_USERS_WITH_CLASS = "GET_USERS_WITH_CLASS";
export const GET_USERCLASSES = "GET_USERCLASSES";

//UserForm
export const CHANGE_USER_FORM_MODE = "CHANGE_USER_FORM_MODE";
export const USER_CLICKED = "USER_CLICKED";
export const FILL_FORM = "FILL_FORM";
export const SNACKBAR = "SNACKBAR";
export const POST_USER_NEW = "POST_USER_NEW";
export const POST_USER_UPDATE = "POST_USER_UPDATE";
export const POST_USER_DELETE = "POST_USER_DELETE";

//Classform
export const CHANGE_CLASS_FORM_MODE = "CHANGE_CLASS_FORM_MODE";
export const CLASS_CLICKED = "CLASS_CLICKED";
export const FILL_CLASS_FORM = "FILL_CLASS_FORM";
export const POST_CLASS_NEW = "POST_CLASS_NEW";
export const POST_CLASS_UPDATE = "POST_CLASS_UPDATE";
export const POST_CLASS_DELETE = "POST_CLASS_DELETE";

//Statistics
export const GET_PROJECTS_PER_REQUIREMENT = "GET_PROJECTS_PER_REQUIREMENT";