/**
 * Contains action types for redux.
 * @module redux/types
 */

//Project
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const GET_REQUIREMENTS_BY_PROJECT_ID = "GET_REQUIREMENTS_BY_PROJECT_ID";
export const POST_REQUIREMENT_TO_PROJECT = "POST_REQUIREMENT_TO_PROJECT";
export const DELETE_REQUIREMENT_TO_PROJECT = "DELETE_REQUIREMENT_TO_PROJECT";

//Requirement
export const GET_ALL_REQUIREMENTS = "GET_ALL_REQUIREMENTS";
export const GET_ALL_CATEGORY_NAMES = "GET_CATEGORIES";
export const UPDATE_FILTER_REQUIREMENT_LIST = "UPDATE_FILTER_REQUIREMENT_LIST";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_REQUIREMENT = "UPDATE_REQUIREMENT";

//SideMenu
export const CHANGE_SIDE_MENU_MODE = "CHANGE_SIDE_MENU_MODE";

//User
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USERS = "GET_USERS";
export const GET_USERS_WITH_CLASS = "GET_USERS_WITH_CLASS";
export const GET_USERCLASSES = "GET_USERCLASSES";

//UserForm
export const CHANGE_USER_FORM_MODE = "CHANGE_USER_FORM_MODE";
export const USER_CLICKED = "USER_CLICKED";
export const FILL_FORM = "FILL_FORM";
export const SNACKBAR = "SNACKBAR";
export const POST_USER_NEW = "POST_USER_NEW";
export const POST_USER_UPDATE = "POST_USER_UPDATE";
export const POST_USER_DELETE = "POST_USER_DELETE";

//Classform
export const CHANGE_CLASS_FORM_MODE = "CHANGE_CLASS_FORM_MODE";
export const CLASS_CLICKED = "CLASS_CLICKED";
export const FILL_CLASS_FORM = "FILL_CLASS_FORM";
export const POST_CLASS_NEW = "POST_CLASS_NEW";
export const POST_CLASS_UPDATE = "POST_CLASS_UPDATE";
export const POST_CLASS_DELETE = "POST_CLASS_DELETE";